### ISSUE TITLE
phue module import broke

### ISSUE THREAD

**Issue by adamc199** [ChristopherRogers1991/mycroft-hue#12]
Overnight the skill stopped working.
I have no idea what changed.
Here's the pertinent error:
14:38:30.789 - mycroft.skills.core:load_skill:144 - ERROR - Failed to load skill: mycroft-hue
  File "/opt/mycroft/skills/mycroft-hue/__init__.py", line 24, in <module>
    from phue import Bridge

I re-ran pip on requirements and phue appears installed:
phue                      - A Philips Hue Python library
  INSTALLED: 1.0 (latest)
hue-sensors-phue          - Tools for reading the state of Philips Hue sensors

Any help is appreciated.

**Comment by ChristopherRogers1991** [comment]
Hey @adamc199,

Thanks for reporting this issue.

The Mycroft team have made a number of big updates over the past two weeks or so, and I've unfortunately not had the time to catch this up to the new standards. I would imagine this is related to those changes, however, at the moment, I'm not sure why this would fall to work if you have phue installed in the virtual environment - according to https://github.com/studioimaginaire/phue/blob/master/README.md, python 3 is supported.

I'll see if I can reproduce the error tonight, or some time this weekend, and see if I can resolve it.

Best,

Chris

**Comment by adamc199** [comment]
Thanks for responding Chris.
 My knowledge of python and coding in general is limited, but I'll gladly help testing or breaking if you need it. I had the skill working extremely well until the update and I'm jonesin' without it.

Thanks for the work and I'll be here if I can help

Adam

**Comment by adamc199** [comment]
PS to above: I am running it on a Mark1

**Comment by glidarlars** [comment]
Hi.

Exactly in the same situation as adamc199.

Running on mark 1 and this is the skill that I use most no question about it.

/lars

**Comment by ChristopherRogers1991** [comment]
Hey @adamc199 and @glidarlars,

What I've discovered is that the failing import seems to be related to Mycroft moving to a new virtual environment, created with venv instead of virtualenv (you can see the note about this here: https://mycroft.ai/blog/python-2-7-python-3-4/#virtual-environment). When I checked the newly created environment on my desktop, it lacked the `phue` library. For testing I manually installed `phue` in the new in the venv, at which point I hit some python2/python3 incompatibilities. I've corrected those, and the skill is now working just fine on my desktop.

I am having some trouble testing on my Mark 1 at the moment, so if either (or both) of you could test it out, I'd really appreciate it. For resolving the virtualenv -> venv issue on the Mark 1, the easiest thing to do is probably to uninstall, and then reinstall the skill. Otherwise, you can find the new venv, and install the library there manually. I was able to find it on my desktop by finding the pid for one of the Mycroft services (`ps -ef | grep mycroft`), then using `lsof -p <pid>` to find the open files that process was using, and looking for `venv`. Once I found that, it was the standard `source <path/to/venv>/bin/activate`, then `pip install phue` to get it installed.

-Chris

**Comment by adamc199** [comment]
Chris,

Uninstalled with msm and installed again
Install failed. Log below:

pi@mark_1:~/skills $ sudo msm install https://github.com/ChristopherRogers1991/mycroft-hue
INFO - Downloading skill: https://github.com/ChristopherRogers1991/mycroft-hue
INFO - Installing requirements.txt for mycroft-hue
PipRequirementsException:
Pip returned code 1:

Exception:
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/basecommand.py", line 228, in main
    status = self.run(options, args)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/commands/install.py", line 241, in run
    with self._build_session(options) as session:
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/basecommand.py", line 81, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/download.py", line 338, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/download.py", line 101, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 120, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 634, in linux_distribution
    self.version(),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 688, in version
    self.lsb_release_attr('release'),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 836, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 522, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 933, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(_main())
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/__init__.py", line 246, in main
    return command.main(cmd_args)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/basecommand.py", line 264, in main
    timeout=min(5, options.timeout)) as session:
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/basecommand.py", line 81, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/download.py", line 338, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_internal/download.py", line 101, in user_agent
    zip(["name", "version", "id"], distro.linux_distribution()),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 120, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 634, in linux_distribution
    self.version(),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 688, in version
    self.lsb_release_attr('release'),
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 836, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 522, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/pip/_vendor/distro.py", line 933, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/usr/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1


I'm going to try to follow your venv instructions now

AC

**Comment by ChristopherRogers1991** [comment]
Hey @adamc199,

Checkout https://stackoverflow.com/questions/44967202/pip-is-showing-error-lsb-release-a-returned-non-zero-exit-status-1#44967506. The error above looks like a pip/python version mismatch.

-Chris

**Comment by adamc199** [comment]
Chris,

I made the LBS change and no matter what I try or as which user (mycroft, sudo or pi) I get the same final error on the install:

(mycroft-core) mycroft@mark_1:/opt/mycroft/skills$ pip install hue
Collecting hue
  Downloading https://files.pythonhosted.org/packages/4e/d6/e0fd54f9f554cf786142217c037cbd35d24e819c1b65b83daea7acc6a0ad/hue-0.1.0.tar.gz
Requirement already satisfied: requests in /opt/venvs/mycroft-core/lib/python3.4/site-packages (from hue) (2.13.0)
Collecting ColorPy (from hue)
  Downloading https://files.pythonhosted.org/packages/99/fc/3f4908f7e643e4e912bacee899e4b11488486259e7fc5739feaab09520a8/colorpy-0.1.1.tar.gz (86kB)
    100% |████████████████████████████████| 92kB 575kB/s
Collecting numpy (from hue)
  Downloading https://files.pythonhosted.org/packages/b0/2b/497c2bb7c660b2606d4a96e2035e92554429e139c6c71cdff67af66b58d2/numpy-1.14.3.zip (4.9MB)
    100% |████████████████████████████████| 4.9MB 1.1MB/s
Building wheels for collected packages: hue, ColorPy, numpy
  Running setup.py bdist_wheel for hue ... done
  Stored in directory: /home/mycroft/.cache/pip/wheels/12/77/e9/64e202459965cbc553a68a0d74c72651ef63f67e6e3545e0f7
  Running setup.py bdist_wheel for ColorPy ... done
  Stored in directory: /home/mycroft/.cache/pip/wheels/1f/64/56/284e8cbe090a3cf5db68d7d5f97b71090b9c5b97fc1e6a7217
  Running setup.py bdist_wheel for numpy ... done
  Stored in directory: /home/mycroft/.cache/pip/wheels/29/74/5c/331da973b82cedd300e088ad58bd241c4c8857dd6faf5433eb
Successfully built hue ColorPy numpy
Installing collected packages: ColorPy, numpy, hue
Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/opt/venvs/mycroft-core/lib/python3.4/site-packages/colorpy-0.1.1.dist-info'
Consider using the `--user` option or check the permissions.

How do I use the --user option? Nothing about it in the pip man page. Can't figure that one out

AC

**Comment by adamc199** [comment]
Additionally, if I do it as root I get:
(mycroft-core) root@mark_1:/opt/mycroft/skills# pip install phue
Requirement already satisfied: phue in /opt/venvs/mycroft-core/lib/python3.4/site-packages (1.0)
(mycroft-core) root@mark_1:/opt/mycroft/skills#

But it still fails to install

AC

**Comment by ChristopherRogers1991** [comment]
Hey @adamc199,

It looks like you mistyped the name of the library in the first command (you typed `pip install hue` rather than `pip install phue`). From the second, it looks like it's claiming that it's already installed. Can you try removing it, and then reinstalling it?

Additionally, just to note, it appears the the Mycroft team have already started with their skill branching stuff described here: https://mycroft.ai/blog/skill-branching-18-02/. I've opened https://github.com/MycroftAI/mycroft-skills/pull/348 to see if I can get it added (which should mean that it'll be installable via `msm` again).

-Chris

**Comment by adamc199** [comment]
OK. I did this:

```
(mycroft-core) root@mark_1:/opt/mycroft/skills# pip uninstall phue
Uninstalling phue-1.0:
  Would remove:
    /opt/venvs/mycroft-core/lib/python3.4/site-packages/phue-1.0.dist-info/*
    /opt/venvs/mycroft-core/lib/python3.4/site-packages/phue.py
Proceed (y/n)? y
  Successfully uninstalled phue-1.0
(mycroft-core) root@mark_1:/opt/mycroft/skills# pip install phue
Collecting phue
Installing collected packages: phue
Successfully installed phue-1.0
(mycroft-core) root@mark_1:/opt/mycroft/skills#
```

Then restarted the mycroft-skills service

I got a NEW error from the logfile (which is encouraging)

```
~~~~t.skills.core:load_skill:105 - INFO - ATTEMPTING TO LOAD SKILL: mycroft-hue.christopherrogers1991 with ID mycroft-hue.christopherrogers1991
16:46:15.946 - mycroft.skills.core:load_skill:144 - ERROR - Failed to load skill: mycroft-hue.christopherrogers1991
Traceback (most recent call last):
File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/skills/core.py", line 120, in load_skill
skill = skill_module.create_skill()
File "/opt/mycroft/skills/mycroft-hue.christopherrogers1991/__init__.py", line 465, in create_skill
return PhillipsHueSkill()
File "/opt/mycroft/skills/mycroft-hue.christopherrogers1991/__init__.py", line 94, in __init__
self.brightness_step = int(self.settings.get('brightness_step'))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

I then added the conf lines to /home/mycroft/.mycroft/mycroft.conf

I tried with the conf file with and without the IP address of my bridge, but receive the same error:

```
~~~~t.skills.core:load_skill:105 - INFO - ATTEMPTING TO LOAD SKILL: mycroft-hue.christopherrogers1991 with ID mycroft-hue.christopherrogers1991
16:50:59.344 - mycroft.skills.core:load_skill:144 - ERROR - Failed to load skill: mycroft-hue.christopherrogers1991
Traceback (most recent call last):
File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/skills/core.py", line 127, in load_skill
skill.initialize()
File "/opt/mycroft/skills/mycroft-hue.christopherrogers1991/__init__.py", line 290, in initialize
self._attempt_connection()
File "/opt/mycroft/skills/mycroft-hue.christopherrogers1991/__init__.py", line 170, in _attempt_connection
self.ip = _discover_bridge()
File "/opt/mycroft/skills/mycroft-hue.christopherrogers1991/__init__.py", line 450, in _discover_bridge
sock.sendto(ssdpRequest, (SSDP_ADDR, SSDP_PORT))
TypeError: 'str' does not support the buffer interface

```

Getting closer for sure!

AC

**Comment by ChristopherRogers1991** [comment]
Ok, I've got to be offline for a few hours, so I'll be unable to continue working with this for a while. If you want to try to hand-jam this, just to get it working, you could try replacing [these four lines](https://github.com/ChristopherRogers1991/mycroft-hue/blob/master/__init__.py#L167-L170) with `self.ip = '<your hub ip>`, e.g. `self.ip = '192.168.1.9'`. The file should live in `/opt/mycroft/skills/mycroft-hue`.

**Comment by adamc199** [comment]
That totally worked Chris.
Thank you for spending your time getting me back up and running. 
I am here to test your next merge whenever you need me. Happy to do scratch installs including removing the illustrious phue module :-)

AC

**Comment by glidarlars** [comment]
hi @adamc199 could you do a super easy to understand step by step guide?

I havent really tried anything with the Mark 1 yet (time issue) so is a total newbee so please have that in mind.

Thanks in advance.

Br,

Lars

**Comment by adamc199** [comment]
Lars,
I don't think that would be very helpful at this stage. The temporary workaround would likely be different for many and moot by the time this skill is updated in the new Mycroft architecture and release methodology.

I suggest you look at a few simpler skills first, like the flip-a-coin skill if you are interested in installing more skills and modifying them. 

AC

**Comment by glidarlars** [comment]
Hi @ChristopherRogers1991

Now it works again!!! And I have actually not done anything... So looks something change again.

Great anyway!

Lars

**Comment by ChristopherRogers1991** [comment]
Glad to hear it's working for both of you. Hoping I'll have time this weekend to add the automated tests necessary to get this back into the skills repo.

**Comment by glidarlars** [comment]
Hi

Now again the hue skilled has stoped working. Do you see that its a new update in mycroft that makes it fail?

So you think its still just to wait and it will start working again?

Have started to realy miss this when it stops working.

Lars

**Comment by ChristopherRogers1991** [comment]
Can you try installing from master? It was working for me as of last night.
You'll probably need to use msm to uninstall it, and then `msm install
https://github.com/ChristopherRogers1991/mycroft-hue.git`

**Comment by glidarlars** [comment]
Hi

Planed to try to connect to my mark 1 today to reinstalling the HUE skill as you suggested. But just before, I did again ask Mycroft "turn on my lights" and now it worked again! 
Litle confusing...
So now im happy again.
But I have a 2nd question that i would like advice on if you have.
I have philips lights in bedroom, kitchen and living room. I can turn on/off all lights and dim or set scene for all rooms at once and seperatley for the living room.
But i cant change bedroom or kitchen without effecting everything?
Is it possible to fix by creating some new name or scenes in hue app do you think?
In the bed room i also have a remote connected but the kitchen has nothing like that.

Thanks again for a great skill!!!

Lars

**Comment by ChristopherRogers1991** [comment]
The skill should register all of the groups that are stored on the bridge, so if you use the official hue app to create a new group (or a new room - a room is a special group that enforces that individual lights only belong to a single room - I believe current versions of the hue app only support rooms, while older versions only support groups), Mycroft should discover them after a restart.

Note that some third party apps do not store groups on the bridge, the just store them in their own database, so the official app is the best to ensure Mycroft will be able to pick them up.

Also, note that you can set a default group, either at https://home.mycroft.ai, or in the local config. Out of the box, the default group is group 0, which is all of your lights. You can change that to any other group, and then any commands that do not specify a group will act only on the default group you've specified.

For example, if you set the default group to 'bedroom' (assuming that is a valid group), and you say "Hey Mycroft, turn off the lights," he would only turn off the lights in the 'bedroom' group. You could still say 'turn off the lights in the kitchen,' or more generally, 'turn off the lights in <some group name>,' to control the lights that are part of another group.

Let me know if that answers your question.

**Comment by glidarlars** [comment]
Great! Thanks it was the answer I looked for! Will restart Mycroft and see if it then finds my new rooms! 
And great that the deafult could be set to different groups, planning to get the outdoor lamps and dont want them to be controlled by mycroft.

By the way do you know why my unit temporary stops working?

Br,

Lars

**Comment by ChristopherRogers1991** [comment]
Are you asking why the hue skill stops working from time to time? Or does the unit stop working as a whole?

Assuming you are asking about the hue skill specifically, I'm not sure. There's been a bit of a shake-up in the Mycroft world recently, as they moved to python 3, and implemented a new system for skill approval/management. There have definitely been some bumps along the way, and based on when you started having trouble, I believe some of the issues may have been related to that. That's just a guess, though.

**Comment by glidarlars** [comment]
Ok thanks. And yes that was my question.
Lets hope it becomes more stable now.
Thanks again!
Lars

**Comment by glidarlars** [comment]
Hi again...

I now have also the hue outdoor lights that i plan to fully run on "at sunset / at sunrise" and not be affected by my "mycroft turn off the lights".
I guess the outdoor lights will also belong to group 0 so is it possible to put the default group to groups instead, like bedroom, kitchen and living room?

Or should i use your new skill that I saw on youtube where you control several things programd oraly by one comand. 

Lars

**Comment by ChristopherRogers1991** [comment]
Updating the default group option to allow a list of values is probably doable, but I don't know that it's something I'll be able to prioritize in the short term (though PRs are welcome, if you're a developer). If you'd like this to be added, please open another issue here on guthub, and tag it as a feature. That'll give us a clean issue to track.

As an alternative in the meantime, you could create a group called 'indoor' that contains all of the lights in the kitchen, bedroom, etc. The caveat here is that I believe the current version of the hue app only allows you to create 'rooms' (which are groups with the restriction that a light can only be a member of a single room), so you'd either need to use the old version of their app, a third party app, or their api directly, in order to create the group.

The routine skill is another valid alternative, if you want to give that a shot. As a note, you'd probably want to give the routine a short name (e.g. 'bedtime') to allow for flexible phrasing (when you want to trigger a routine, the name must match exactly, so a long name is more rigid), and may want to avoid using the word 'lights' (e.g. 'lights out' would be a poor name for the routine). Having 'lights' in the name may work, but there's potential to trip Mycroft up, and have him confuse the two skills.

Best,

Chris

**Comment by glidarlars** [comment]
Ok thanks! I think Ill give the routine skill a try.

And thanks again!

Lars
